# Generated by Django 3.2.8 on 2021-10-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_relationsships', '0002_frameworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('frameworks', models.ManyToManyField(to='dj_relationsships.Frameworks')),
            ],
        ),
    ]
